# Generated by Django 6.0.6 on 2026-06-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CamMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('generation_delta_time', models.PositiveIntegerField()),
                ('station_type', models.PositiveIntegerField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('altitude_m', models.FloatField(blank=True, null=True)),
                ('speed_mps', models.FloatField(blank=True, null=True)),
                ('heading_deg', models.FloatField(blank=True, null=True)),
                ('drive_direction', models.CharField(blank=True, max_length=32)),
                ('raw_hex', models.TextField()),
                ('decoded', models.JSONField()),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
